version: 2
jobs:
  build:
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - checkout
      - run: curl https://install.meteor.com/ | sh
      - run: meteor &
      - run: add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - run: apt update
      - run: apt install g++-7 -y
      - run: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
      - run: git submodule update --init --recursive
      - run: cd / && curl -O https://storage.googleapis.com/golang/go1.10.linux-amd64.tar.gz && tar zxvf go1.10.linux-amd64.tar.gz
      - run:
          name: Setting up Environment Variables for Golang
          command: |
            echo 'export GOROOT="/go"' >> $BASH_ENV
            echo 'export GOPATH="/root/go"' >> $BASH_ENV
            echo 'export GOGITHUB="$GOPATH/src/github.com"' >> $BASH_ENV
            echo 'export PATH="$PATH:/go/bin/:$GOGITHUB/haya14busa/goverage:$GOGITHUB/schrej/godacov/"' >> $BASH_ENV
      - run: go get github.com/magiconair/properties/assert
      - run: mkdir -p $GOGITHUB/theQRL/go-qrl
      - run: cp -r . $GOGITHUB/theQRL/go-qrl/
      - run: cd $GOGITHUB/theQRL && git clone https://github.com/cyyber/qrllib && cd qrllib && git submodule update --init
      - run: cd $GOGITHUB/theQRL/qrllib/ && cmake -DBUILD_GO=ON && make
      - run: cd $GOGITHUB/theQRL && git clone https://github.com/cyyber/qryptonight && cd qryptonight && git submodule update --init
      - run: cd $GOGITHUB/theQRL/qryptonight/ && cmake -DBUILD_GO=ON -DSANITIZE_ADDRESS=OFF -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5 && make
      - run: go get -u github.com/schrej/godacov && cd $GOGITHUB/schrej/godacov && go build
      - run: go get -u github.com/haya14busa/goverage && cd $GOGITHUB/haya14busa/goverage && go build
      - run: cd $GOGITHUB/theQRL/go-qrl && go get -v -t -d ./...
      - run: cd $GOGITHUB/theQRL/go-qrl && goverage -v -coverprofile=coverage.out ./...
      - run: if [[ -v CODACY_PROJECT_TOKEN ]]; then cd $GOGITHUB/theQRL/go-qrl && godacov -t $CODACY_PROJECT_TOKEN -r ./coverage.out -c $CIRCLE_SHA1 || echo "failed"; fi

workflows:
  version: 2
  build_all:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
