// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"

	"github.com/theQRL/go-qrl/common"
	"github.com/theQRL/go-qrl/common/hexutil"
)

var _ = (*withdrawalMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (w Withdrawal) MarshalJSON() ([]byte, error) {
	type Withdrawal struct {
		Index     hexutil.Uint64 `json:"index"          gencodec:"required"`
		Validator hexutil.Uint64 `json:"validatorIndex" gencodec:"required"`
		Address   common.Address `json:"address"        gencodec:"required"`
		Amount    hexutil.Uint64 `json:"amount"         gencodec:"required"`
	}
	var enc Withdrawal
	enc.Index = hexutil.Uint64(w.Index)
	enc.Validator = hexutil.Uint64(w.Validator)
	enc.Address = w.Address
	enc.Amount = hexutil.Uint64(w.Amount)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (w *Withdrawal) UnmarshalJSON(input []byte) error {
	type Withdrawal struct {
		Index     *hexutil.Uint64 `json:"index"          gencodec:"required"`
		Validator *hexutil.Uint64 `json:"validatorIndex" gencodec:"required"`
		Address   *common.Address `json:"address"        gencodec:"required"`
		Amount    *hexutil.Uint64 `json:"amount"         gencodec:"required"`
	}
	var dec Withdrawal
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Index == nil {
		return errors.New("missing required field 'index' for Withdrawal")
	}
	w.Index = uint64(*dec.Index)
	if dec.Validator == nil {
		return errors.New("missing required field 'validatorIndex' for Withdrawal")
	}
	w.Validator = uint64(*dec.Validator)
	if dec.Address == nil {
		return errors.New("missing required field 'address' for Withdrawal")
	}
	w.Address = *dec.Address
	if dec.Amount == nil {
		return errors.New("missing required field 'amount' for Withdrawal")
	}
	w.Amount = uint64(*dec.Amount)
	return nil
}
