// Code generated by rlpgen. DO NOT EDIT.

package types

import "github.com/theQRL/go-qrl/rlp"
import "io"

func (obj *Header) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	w.WriteBytes(obj.ParentHash[:])
	w.WriteBytes(obj.Coinbase[:])
	w.WriteBytes(obj.Root[:])
	w.WriteBytes(obj.TxHash[:])
	w.WriteBytes(obj.ReceiptHash[:])
	w.WriteBytes(obj.Bloom[:])
	if obj.Number == nil {
		w.Write(rlp.EmptyString)
	} else {
		if obj.Number.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Number)
	}
	w.WriteUint64(obj.GasLimit)
	w.WriteUint64(obj.GasUsed)
	w.WriteUint64(obj.Time)
	w.WriteBytes(obj.Extra)
	w.WriteBytes(obj.Random[:])
	if obj.BaseFee == nil {
		w.Write(rlp.EmptyString)
	} else {
		if obj.BaseFee.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.BaseFee)
	}
	if obj.WithdrawalsHash == nil {
		w.WriteBytes(EmptyWithdrawalsHash[:])
	} else {
		w.WriteBytes(obj.WithdrawalsHash[:])
	}
	w.ListEnd(_tmp0)
	return w.Flush()
}
